# Generated by Django 5.2.4 on 2025-08-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_abroad_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cities_lived',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sibling_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
